name: Run Action Locally

on:
  # Trigger the workflow on pull request to the dev branch
  workflow_dispatch:
  push:
    branches:
      [main]

jobs:
  run_action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Doop dee doop
          echo Doop a dee doop

      # Executes a file
      - name: Run script
        shell: bash
        run: |
          node ./.github/workflows/justAScript.js
